name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'tw2mp_groupie-tracker@tw2mp.ftp.infomaniak.com'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: echo before && whoami && pwd && cd /home/clients/3d62e274d4bb2700d62d1fdeef3668fc/sites/groupie-tracker.vitrihome.fr/ && echo after && git pull && echo finish
